package auth

// this module try to:
// 1. Authenticates with the tmp auth token in $HOME/.aws folder, which is generated by prior process
// 2. Gets secrets from AWS-SSM/Parameter-Store

// input: aws-ssm-parameter-path to bk-api-token
// output: parameters

import (
    "fmt"
    "github.com/aws/aws-sdk-go/aws"
    "github.com/aws/aws-sdk-go/service/ssm"
)

